const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close':'Menu'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu'}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu'}});const quote=document.querySelector('#quoteForm');const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);function estimate(){const data=new FormData(quote);let cost=Number(data.get('base')),monthly=Number(data.get('maintenance')||0);cost+=Number(data.get('logo')||0)+Number(data.get('blog')||0);document.querySelector('#total').textContent=usd(cost);document.querySelector('#monthly').textContent=monthly?'+ '+usd(monthly)+'/month maintenance':'';document.querySelector('#estimateField').value=usd(cost)+(monthly?' + '+usd(monthly)+'/month':'');}quote.addEventListener('change',estimate);estimate();document.querySelector('#useEstimate').addEventListener('click',()=>{const msg=document.querySelector('#message');const choices=[...quote.querySelectorAll('input:checked')].map(x=>x.parentElement.textContent.trim()).join('; ');msg.value='I’m interested in: '+choices+'. Estimated starting cost: '+document.querySelector('#estimateField').value+'.\n\nProject details: ';document.querySelector('#contact').scrollIntoView({behavior:'smooth'});msg.focus({preventScroll:true})});document.querySelector('#year').textContent=new Date().getFullYear();const form=document.querySelector('#contactForm');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]'),status=document.querySelector('#formStatus');button.disabled=true;button.textContent='Sending…';status.textContent='Sending your project inquiry…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Submission failed');status.textContent='Thanks! Your inquiry has been sent. Dylan will follow up by email.';form.reset();estimate()}catch{status.textContent='Your inquiry could not be sent. Please try again or email ignitewebomaha@yahoo.com. Your details are still here.'}finally{button.disabled=false;button.textContent='Send project inquiry'}});

// One gentle entrance per card; content stays visible without JavaScript.
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
if(!motionPreference.matches && 'IntersectionObserver' in window && typeof Element.prototype.animate==='function'){
 const activeAnimations=new Set();
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;observer.unobserve(entry.target);const animation=entry.target.animate([{opacity:0.4,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'cubic-bezier(.2,.65,.3,1)'});activeAnimations.add(animation);animation.onfinish=()=>activeAnimations.delete(animation)}},{threshold:0.12});
 document.querySelectorAll('.project,.services article,.capability,.process>div').forEach(el=>observer.observe(el));
 motionPreference.addEventListener('change',e=>{if(e.matches){observer.disconnect();activeAnimations.forEach(a=>a.cancel());activeAnimations.clear()}});
}
